import {
  Policy,
  Claim,
  DocumentItem,
  LifeStageEvent,
  EcosystemService,
  CoverageGap,
  AppNotification,
} from './types';

export const INITIAL_POLICIES: Policy[] = [
  {
    id: 'pol-1',
    category: 'Health',
    name: 'Health Secure Ultra',
    provider: 'InsureX Shield Care',
    policyNumber: 'HLT-2026-88910',
    coverageAmount: 500000,
    monthlyPremium: 85,
    annualPremium: 980,
    startDate: '2025-03-15',
    expiryDate: '2026-03-14',
    status: 'Expiring Soon',
    deductible: 500,
    claimSettlementRatio: 99.1,
    coveredMembers: ['Alex Johnson (Self)', 'Sarah Johnson (Spouse)', 'Leo Johnson (Child)', 'Maya Johnson (Child)'],
    keyBenefits: [
      'Cashless hospitalization at 12,000+ network hospitals',
      'Zero co-payment for room rent & ICU',
      'Annual free full-body health checkup for all 4 members',
      '24/7 Unlimited Telemedicine Consultations',
      'Mental Health & Wellness Coaching included',
    ],
    exclusions: ['Cosmetic Surgery', 'Pre-existing conditions during initial 30 days', 'Non-prescription supplements'],
    aiRecommendationBadge: 'Top Family Pick',
    iconName: 'HeartPulse',
    autoRenew: true,
    documentsCount: 4,
  },
  {
    id: 'pol-2',
    category: 'Motor',
    name: 'Auto Guardian Comprehensive',
    provider: 'InsureX Drive Safe',
    policyNumber: 'MTR-2025-44120',
    coverageAmount: 45000,
    monthlyPremium: 62,
    annualPremium: 710,
    startDate: '2025-08-01',
    expiryDate: '2026-07-31',
    status: 'Active',
    deductible: 250,
    claimSettlementRatio: 98.8,
    coveredMembers: ['Tesla Model Y (2024) - VIN: 5YJ3E1EA8NF****'],
    keyBenefits: [
      'Zero Depreciation coverage on all electric vehicle parts & battery',
      '24/7 Unlimited Roadside Assistance & Towing up to 100 miles',
      'EV Charging Lock & Key replacement cover',
      'Cashless garage repair at 4,500+ authorized EV stations',
    ],
    exclusions: ['Driving under influence', 'Normal mechanical wear & tear', 'Unauthorized driver'],
    aiRecommendationBadge: 'EV Optimized',
    iconName: 'Car',
    autoRenew: true,
    documentsCount: 3,
  },
  {
    id: 'pol-3',
    category: 'Life',
    name: 'Term Life Vantage 360',
    provider: 'InsureX Life Heritage',
    policyNumber: 'LIF-2024-99123',
    coverageAmount: 1500000,
    monthlyPremium: 48,
    annualPremium: 550,
    startDate: '2024-01-10',
    expiryDate: '2054-01-09',
    status: 'Active',
    deductible: 0,
    claimSettlementRatio: 99.5,
    coveredMembers: ['Alex Johnson (Insured)', 'Sarah Johnson (Primary Beneficiary)'],
    keyBenefits: [
      'Critical Illness benefit rider (Payout up to $250k on diagnosis)',
      'Accidental Disability lump sum multiplier',
      'Tax savings under Section 80C / 10D',
      'Inflation-adjusted coverage booster (+5% annually)',
    ],
    exclusions: ['Suicide within 12 months', 'Dangerous extreme sports without rider'],
    aiRecommendationBadge: 'Essential Life Net',
    iconName: 'Shield',
    autoRenew: true,
    documentsCount: 5,
  },
  {
    id: 'pol-4',
    category: 'Home',
    name: 'Home Sanctuary Shield',
    provider: 'InsureX Haven',
    policyNumber: 'HOM-2025-33100',
    coverageAmount: 350000,
    monthlyPremium: 32,
    annualPremium: 360,
    startDate: '2025-05-10',
    expiryDate: '2026-05-09',
    status: 'Active',
    deductible: 500,
    claimSettlementRatio: 97.9,
    coveredMembers: ['1044 Willow Creek Lane, San Francisco CA'],
    keyBenefits: [
      'Full structure protection against fire, earthquake & flood',
      'Electronics & valuable contents theft protection',
      'Temporary emergency relocation allowance up to $10,000',
      '24/7 Home Plumbing & Electrical emergency hotline',
    ],
    exclusions: ['Intentional damage', 'War or nuclear hazard'],
    aiRecommendationBadge: 'Property Guard',
    iconName: 'Home',
    autoRenew: false,
    documentsCount: 2,
  },
  {
    id: 'pol-5',
    category: 'Travel',
    name: 'Global Nomad Pass',
    provider: 'InsureX Voyage',
    policyNumber: 'TRV-2026-11029',
    coverageAmount: 100000,
    monthlyPremium: 18,
    annualPremium: 200,
    startDate: '2026-06-01',
    expiryDate: '2026-12-31',
    status: 'Active',
    deductible: 50,
    claimSettlementRatio: 98.4,
    coveredMembers: ['Alex Johnson', 'Sarah Johnson'],
    keyBenefits: [
      'Worldwide emergency medical evacuation ($100k limit)',
      'Flight cancellation & delay reimbursement up to $2,500',
      'Lost luggage & passport replacement assistance',
      'Adventure sports extension rider included',
    ],
    exclusions: ['Unapproved high-risk regions', 'Pre-existing ailments without declaration'],
    aiRecommendationBadge: 'Frequent Traveler Favorite',
    iconName: 'Plane',
    autoRenew: false,
    documentsCount: 1,
  },
  {
    id: 'pol-6',
    category: 'Gadget',
    name: 'Tech Armor Pro',
    provider: 'InsureX Byte Care',
    policyNumber: 'GDT-2026-77821',
    coverageAmount: 3500,
    monthlyPremium: 12,
    annualPremium: 130,
    startDate: '2026-01-15',
    expiryDate: '2027-01-14',
    status: 'Active',
    deductible: 75,
    claimSettlementRatio: 99.0,
    coveredMembers: ['iPhone 16 Pro Max', 'MacBook Pro M3 Max'],
    keyBenefits: [
      'Accidental drop, liquid damage, & screen cracking',
      'Worldwide theft protection with instant police report filing assistance',
      'Same-day door-step pickup & loaner device provided',
    ],
    exclusions: ['Cosmetic scratches not affecting functionality'],
    aiRecommendationBadge: 'Instant Gadget Care',
    iconName: 'Smartphone',
    autoRenew: true,
    documentsCount: 2,
  },
  {
    id: 'pol-7',
    category: 'Pet',
    name: 'Paws & Tail Guardian',
    provider: 'InsureX PetCare',
    policyNumber: 'PET-2026-90812',
    coverageAmount: 15000,
    monthlyPremium: 22,
    annualPremium: 240,
    startDate: '2026-02-01',
    expiryDate: '2027-01-31',
    status: 'Active',
    deductible: 100,
    claimSettlementRatio: 98.2,
    coveredMembers: ['Milo (Golden Retriever, 3 yrs)'],
    keyBenefits: [
      'Vet bill reimbursement up to 90%',
      'Hereditary & chronic condition coverage',
      'Pet loss & theft reward reimbursement',
      '24/7 Tele-vet chat included',
    ],
    exclusions: ['Pre-existing conditions prior to enrollment'],
    aiRecommendationBadge: 'Best for Canines',
    iconName: 'Dog',
    autoRenew: true,
    documentsCount: 2,
  },
  {
    id: 'pol-8',
    category: 'Business',
    name: 'Startup Cyber & Liability Shield',
    provider: 'InsureX Enterprise',
    policyNumber: 'BUS-2026-30219',
    coverageAmount: 1000000,
    monthlyPremium: 145,
    annualPremium: 1600,
    startDate: '2026-01-01',
    expiryDate: '2026-12-31',
    status: 'Active',
    deductible: 1000,
    claimSettlementRatio: 99.4,
    coveredMembers: ['InsureX Labs LLC (12 Employees)'],
    keyBenefits: [
      'Ransomware & cyber data breach liability ($500k)',
      'General commercial third-party liability ($500k)',
      'Key executive travel & office contents protection',
    ],
    exclusions: ['Gross negligence or intentional breach'],
    aiRecommendationBadge: 'SME Cyber Standard',
    iconName: 'Briefcase',
    autoRenew: true,
    documentsCount: 3,
  },
];

export const INITIAL_CLAIMS: Claim[] = [
  {
    id: 'clm-1',
    claimNumber: 'CLM-2026-8921',
    policyId: 'pol-1',
    policyName: 'Health Secure Ultra',
    category: 'Health',
    incidentType: 'Outpatient Emergency ER Visit - Ankle Fracture',
    incidentDate: '2026-08-02',
    claimAmount: 2450,
    approvedAmount: 2450,
    status: 'Approved',
    estimatedSettlementTime: 'Disbursing in 2 hours',
    fraudRiskLevel: 'Low Risk',
    timeline: [
      {
        title: 'Claim Submitted',
        description: 'Hospital bill & X-Ray reports uploaded via InsureX app',
        timestamp: 'Aug 02, 11:20 AM',
        completed: true,
      },
      {
        title: 'AI Document Verification',
        description: 'Medical codes (ICD-10-CM S82.8) verified instantly by Gemini AI OCR',
        timestamp: 'Aug 02, 11:21 AM',
        completed: true,
      },
      {
        title: 'Automated Fraud & Eligibility Scan',
        description: 'Zero anomalies detected. Low risk score (99.4% confidence)',
        timestamp: 'Aug 02, 11:22 AM',
        completed: true,
      },
      {
        title: 'Adjuster Review & Payout Sanction',
        description: 'Sanctioned for direct bank transfer to UCSF Health Network',
        timestamp: 'Aug 03, 09:15 AM',
        completed: true,
        current: true,
      },
      {
        title: 'Funds Disbursed',
        description: 'Instant ACH settlement to beneficiary account',
        timestamp: 'Pending (Est. 2 hours)',
        completed: false,
      },
    ],
    uploadedDocuments: ['ER_Admission_Bill.pdf', 'XRay_Radiology_Report.png', 'Doctor_Prescription.pdf'],
    notes: 'Pre-approved under cashless network guarantee. Patient copay $0.',
  },
  {
    id: 'clm-2',
    claimNumber: 'CLM-2026-4402',
    policyId: 'pol-2',
    policyName: 'Auto Guardian Comprehensive',
    category: 'Motor',
    incidentType: 'Windshield Stone Chip Crack Repair',
    incidentDate: '2026-07-18',
    claimAmount: 620,
    approvedAmount: 620,
    status: 'Disbursed',
    estimatedSettlementTime: 'Completed on Jul 19',
    fraudRiskLevel: 'Low Risk',
    timeline: [
      {
        title: 'Claim Submitted',
        description: 'Photos of cracked glass uploaded',
        timestamp: 'Jul 18, 03:40 PM',
        completed: true,
      },
      {
        title: 'AI Damage Inspection',
        description: 'Computer vision estimated repair cost $620 at Safelite AutoGlass',
        timestamp: 'Jul 18, 03:41 PM',
        completed: true,
      },
      {
        title: 'Approved & Settled',
        description: '$620 disbursed to Safelite Cashless Garage',
        timestamp: 'Jul 19, 10:00 AM',
        completed: true,
      },
    ],
    uploadedDocuments: ['Windshield_Photo_1.jpg', 'Safelite_Estimate.pdf'],
  },
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-1',
    title: 'Health Policy Bond & Member Cards',
    category: 'Certificate',
    policyName: 'Health Secure Ultra',
    uploadDate: 'Mar 15, 2025',
    fileSize: '2.4 MB',
    fileType: 'PDF',
    aiSummary: 'Includes digital health cards for Alex, Sarah, Leo, Maya. Policy cover $500k with zero room copay.',
  },
  {
    id: 'doc-2',
    title: 'UCSF Emergency ER Bill & Discharge Summary',
    category: 'Medical Report',
    policyName: 'Health Secure Ultra',
    uploadDate: 'Aug 02, 2026',
    fileSize: '4.1 MB',
    fileType: 'PDF',
    aiSummary: 'Hospital bill for right ankle immobilization. Total $2,450. ICD-10 S82.8 verified for 100% cashless payout.',
  },
  {
    id: 'doc-3',
    title: 'Tesla Model Y Registration & Insurance Card',
    category: 'Vehicle Papers',
    policyName: 'Auto Guardian Comprehensive',
    uploadDate: 'Aug 01, 2025',
    fileSize: '1.8 MB',
    fileType: 'PDF',
    aiSummary: 'Official proof of insurance for DMV compliance. Policy #MTR-2025-44120.',
  },
  {
    id: 'doc-4',
    title: 'Home Deed & Structure Assessment',
    category: 'Certificate',
    policyName: 'Home Sanctuary Shield',
    uploadDate: 'May 10, 2025',
    fileSize: '5.2 MB',
    fileType: 'PDF',
    aiSummary: 'Structural valuation report confirming $350k replacement cost for 1044 Willow Creek Lane.',
  },
];

export const LIFE_STAGE_EVENTS: LifeStageEvent[] = [
  {
    id: 'ls-grad',
    title: 'Graduation & Launch',
    icon: 'GraduationCap',
    badge: 'First Steps',
    description: 'Transitioning from campus to early career. Protect your laptop, personal gadgets, and initial health starter.',
    recommendedPolicies: [
      {
        category: 'Gadget',
        name: 'Tech Armor Starter',
        reason: 'Essential protection for your primary work laptop and phone against spills, drops & theft.',
        estimatedPremium: 10,
        coverageAmount: 2500,
      },
      {
        category: 'Health',
        name: 'Youth Health Kickstart',
        reason: 'Affordable health coverage with free annual preventive checkups and tele-consults.',
        estimatedPremium: 35,
        coverageAmount: 100000,
      },
    ],
    lifeTips: [
      'Opt for higher deductibles while young to keep premiums low',
      'Keep digital copies of all academic transcripts in your InsureX vault',
      'Build a habit of checking your credit & coverage scores early',
    ],
  },
  {
    id: 'ls-job',
    title: 'First Career Job',
    icon: 'Briefcase',
    badge: 'Income & Stability',
    description: 'Securing stable salary. Time to add Income Protection, Term Life, and supplement employer health plans.',
    recommendedPolicies: [
      {
        category: 'Life',
        name: 'Term Life Essential',
        reason: 'Lock in lowest lifelong term rates while in your 20s.',
        estimatedPremium: 25,
        coverageAmount: 750000,
      },
      {
        category: 'Health',
        name: 'Top-Up Health Supercharge',
        reason: 'Bridges employer insurance gaps for major unexpected hospitalizations.',
        estimatedPremium: 20,
        coverageAmount: 250000,
      },
    ],
    lifeTips: [
      'Employer group insurance usually lapses if you change jobs; maintain a personal core policy',
      'Set up auto-pay to earn a 5% loyalty discount',
    ],
  },
  {
    id: 'ls-vehicle',
    title: 'New Vehicle Purchase',
    icon: 'Car',
    badge: 'On the Road',
    description: 'Bought a new car or EV? Protect your investment with zero depreciation and EV battery safeguards.',
    recommendedPolicies: [
      {
        category: 'Motor',
        name: 'Auto Guardian Comprehensive',
        reason: 'Includes zero-dep, roadside assistance, towing, and battery degradation cover.',
        estimatedPremium: 62,
        coverageAmount: 45000,
      },
    ],
    lifeTips: [
      'Store digital insurance QR code on your phone lock screen for DMV/traffic checks',
      'Connect vehicle telemetry for up to 20% safe-driver cashbacks',
    ],
  },
  {
    id: 'ls-home',
    title: 'Buying a Home',
    icon: 'Home',
    badge: 'Property & Equity',
    description: 'Mortgage & home ownership require property protection against fire, floods, and loan protection.',
    recommendedPolicies: [
      {
        category: 'Home',
        name: 'Home Sanctuary Shield',
        reason: 'Covers physical house structure, interior electronics, and temporary living expenses.',
        estimatedPremium: 32,
        coverageAmount: 350000,
      },
    ],
    lifeTips: [
      'Take photos of high-value electronics and upload them to InsureX Document Locker for instant claim proof',
      'Bundle Home + Auto for an immediate 15% discount',
    ],
  },
  {
    id: 'ls-marriage',
    title: 'Marriage & Partnership',
    icon: 'Heart',
    badge: 'Shared Future',
    description: 'Combining lives and assets. Upgrade to a Family Health Floater and joint financial security.',
    recommendedPolicies: [
      {
        category: 'Health',
        name: 'Family Health Security Floater',
        reason: 'Single floater sum insured shared between both partners with maternity benefits.',
        estimatedPremium: 65,
        coverageAmount: 300000,
      },
      {
        category: 'Life',
        name: 'Joint Term Vantage 360',
        reason: 'Dual payout protection securing both partners against unforeseen financial loss.',
        estimatedPremium: 48,
        coverageAmount: 1500000,
      },
    ],
    lifeTips: [
      'Update beneficiaries across all active policies',
      'Check if spouse has duplicate coverage to avoid overpaying premiums',
    ],
  },
  {
    id: 'ls-parent',
    title: 'Becoming a Parent',
    icon: 'Baby',
    badge: 'Family First',
    description: 'New baby on board! Expand health floater to cover newborns from Day 1 and secure education protection.',
    recommendedPolicies: [
      {
        category: 'Health',
        name: 'Newborn & Child Ultra Care',
        reason: 'Covers infant vaccination, pediatric ER care, and zero co-pay pediatric consults.',
        estimatedPremium: 85,
        coverageAmount: 500000,
      },
    ],
    lifeTips: [
      'Notify your health insurer within 30 days of birth for instant baby inclusion',
      'Add child critical illness rider to term policies for piece of mind',
    ],
  },
  {
    id: 'ls-travel',
    title: 'International Travel',
    icon: 'Plane',
    badge: 'Global Explorer',
    description: 'Heading overseas for work or vacation? Get worldwide medical evacuation and trip delay cover.',
    recommendedPolicies: [
      {
        category: 'Travel',
        name: 'Global Nomad Pass',
        reason: 'Covers overseas ER, passport loss, flight cancellations, and alpine sports.',
        estimatedPremium: 18,
        coverageAmount: 100000,
      },
    ],
    lifeTips: [
      'Check destination visa travel insurance requirements (e.g. Schengen 30k Euro min)',
      'Keep 24/7 InsureX emergency hotline saved offline in your phone',
    ],
  },
  {
    id: 'ls-retirement',
    title: 'Retirement Planning',
    icon: 'Sun',
    badge: 'Golden Years',
    description: 'Ensuring financial independence and lifelong healthcare without depleting savings.',
    recommendedPolicies: [
      {
        category: 'Health',
        name: 'Senior Health Care Plus',
        reason: 'Guaranteed lifelong renewability with coverage for pre-existing cardiac & orthopedic care.',
        estimatedPremium: 110,
        coverageAmount: 500000,
      },
    ],
    lifeTips: [
      'Focus on zero-copay health policies with restore benefits',
      'Utilize InsureX annuity insights for stable monthly pension payouts',
    ],
  },
];

export const ECOSYSTEM_SERVICES: EcosystemService[] = [
  {
    id: 'eco-1',
    title: '24/7 AI Telemedicine & Video Consults',
    category: 'Health',
    icon: 'Stethoscope',
    description: 'Connect with board-certified doctors in under 2 minutes. Free & unlimited for Health policyholders.',
    partnerName: 'Teladoc & HealthX Network',
    discountOrPerk: '100% Cashless ($0 Copay)',
    actionText: 'Book Instant Consult',
    rating: 4.9,
    locationDependent: false,
  },
  {
    id: 'eco-2',
    title: 'Cashless EV & Motor Garages',
    category: 'Motor',
    icon: 'Wrench',
    description: 'Over 4,500 partner auto repair centers with direct InsureX bill settlement and zero paperwork.',
    partnerName: 'Safelite, Tesla Care & RepairPal',
    discountOrPerk: 'Free Pickup & Drop + Free Inspection',
    actionText: 'Find Nearest Garage',
    rating: 4.8,
    locationDependent: true,
  },
  {
    id: 'eco-3',
    title: '1-Tap Roadside & Towing Dispatch',
    category: 'Motor',
    icon: 'Truck',
    description: 'GPS-tracked emergency towing, battery jumpstart, flat tire swap, and fuel delivery.',
    partnerName: 'InsureX FleetAssist',
    discountOrPerk: 'Free up to 100 miles',
    actionText: 'Request Towing Truck',
    rating: 4.95,
    locationDependent: true,
  },
  {
    id: 'eco-4',
    title: 'Home Repair & Plumbing Emergency',
    category: 'Home',
    icon: 'Hammer',
    description: 'Vetted emergency locksmiths, plumbers, and electricians at your door within 45 minutes.',
    partnerName: 'HandyGuard Express',
    discountOrPerk: '$50 Off First Emergency Visit',
    actionText: 'Dispatch Technician',
    rating: 4.7,
    locationDependent: true,
  },
  {
    id: 'eco-5',
    title: 'Emergency Medical Hospital Finder',
    category: 'Emergency',
    icon: 'Hospital',
    description: 'Locate top-rated cashless network hospitals near your current GPS position with instant pre-approval.',
    partnerName: 'InsureX Cashless Net',
    discountOrPerk: 'Pre-Approved Cashless ER',
    actionText: 'View Network Hospitals',
    rating: 4.9,
    locationDependent: true,
  },
  {
    id: 'eco-6',
    title: 'Flight Delay & Luggage Tracker',
    category: 'Travel',
    icon: 'Compass',
    description: 'Automatic flight status monitoring. Instant lounge access code issued if flight is delayed >2 hours.',
    partnerName: 'FlightAware & PriorityPass',
    discountOrPerk: 'Free VIP Airport Lounge Pass',
    actionText: 'Sync My Flight',
    rating: 4.85,
    locationDependent: false,
  },
  {
    id: 'eco-7',
    title: 'Digital Health Records & Apple Health Sync',
    category: 'Health',
    icon: 'Activity',
    description: 'Securely sync daily step counts, sleep quality, and vitals to earn up to 15% premium renewal discounts.',
    partnerName: 'Apple Health & Google Fit',
    discountOrPerk: 'Earn up to 15% Premium Cashback',
    actionText: 'Connect Fitness Device',
    rating: 4.9,
    locationDependent: false,
  },
];

export const COVERAGE_GAPS: CoverageGap[] = [
  {
    id: 'gap-1',
    title: 'Missing Critical Illness Payout Shield',
    category: 'Health',
    missingFeature: 'No lump-sum cash payout upon diagnosis of cardiac or oncology conditions.',
    currentRisk: 'High out-of-pocket medical expenses during non-hospital recovery periods.',
    recommendedAddon: 'Critical Illness Booster ($250k Cover)',
    estimatedMonthlyCost: 12,
    protectionScoreImpact: +8,
  },
  {
    id: 'gap-2',
    title: 'No Zero Depreciation on Motor Policy',
    category: 'Motor',
    missingFeature: 'Plastic and rubber bumper parts depreciated up to 50% during accident repairs.',
    currentRisk: 'Paying $400 - $800 out-of-pocket during collision claims.',
    recommendedAddon: 'Zero-Dep Bumper-to-Bumper Addon',
    estimatedMonthlyCost: 7,
    protectionScoreImpact: +6,
  },
  {
    id: 'gap-3',
    title: 'Home Electronics & Theft Unprotected',
    category: 'Home',
    missingFeature: 'Structure policy covers walls but lacks high-value gadget content theft rider.',
    currentRisk: 'Laptops, TVs, and jewelry not covered during burglary.',
    recommendedAddon: 'Home Content & Theft Rider ($25k)',
    estimatedMonthlyCost: 5,
    protectionScoreImpact: +5,
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'Policy Renewal Reminder',
    message: 'Health Secure Ultra expires in 35 days. Renew now to retain your 15% No-Claim bonus discount!',
    timestamp: '10 mins ago',
    type: 'renewal',
    read: false,
    actionLink: 'renewals',
  },
  {
    id: 'notif-2',
    title: 'Claim Settlement Approved!',
    message: 'Claim #CLM-2026-8921 for $2,450 (UCSF ER Visit) was approved by AI Adjuster. Funds disbursing.',
    timestamp: '2 hours ago',
    type: 'claim',
    read: false,
    actionLink: 'claims',
  },
  {
    id: 'notif-3',
    title: 'AI Protection Insight',
    message: 'Your Coverage Health Score is 84/100. Adding Critical Illness cover will raise it to 92/100.',
    timestamp: 'Yesterday',
    type: 'ai',
    read: true,
    actionLink: 'coverage-gap',
  },
  {
    id: 'notif-4',
    title: 'Weather Warning Alert',
    message: 'Severe hail storm forecasted in Bay Area tomorrow. Move your Tesla under covered parking!',
    timestamp: '2 days ago',
    type: 'weather',
    read: true,
    actionLink: 'policies',
  },
];
